#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#       Important: this is a minimal stub. The actual gradlew script from
#       https://github.com/gradle/gradle is required for full functionality.
#       Run `gradle wrapper` after installing Gradle to populate the wrapper
#       jar and full scripts.
#
##############################################################################

# Determine the Java command to use to start the JVM.
if [ -z "$JAVA_HOME" ]; then
    echo "JAVA_HOME is not set. Please set it to a JDK 21 installation." >&2
    exit 1
fi

JAVA_EXE="$JAVA_HOME/bin/java"
if [ ! -x "$JAVA_EXE" ]; then
    echo "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
    exit 1
fi

# Resolve wrapper JAR location.
APP_HOME="$(cd "$(dirname "$0")"; pwd)"
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$WRAPPER_JAR" ]; then
    echo "ERROR: $WRAPPER_JAR is missing. Run 'gradle wrapper' to generate it." >&2
    exit 1
fi

exec "$JAVA_EXE" -Dorg.gradle.appname=gradlew -classpath "$WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
